post_show
athanael/diaryJam pull request #10
Opened 2024-11-13 12:57 UTC by zealest

/!\ View à changer

à tester

2024-11-13 20:08 UTC, ArgjentG approved these changes

2024-11-14 07:17 UTC, athanael requested changes
enlever le fichier de création de post

2024-11-14 07:17 UTC, athanael commented on app/views/posts/new.html.erb
J'ai déjà fait ce fichier, à enlever

2024-11-14 11:58 UTC, athanael requested changes
Ajouter dans la vue la partiale d'Argjent pour avoir un affichage uniforme.
Faire le lien entre l'index et la show

2024-11-14 12:33 UTC, merged