création de la ProfilePage
athanael/diaryJam pull request #7
Opened 2024-11-10 16:50 UTC by 0Imad0

2024-11-10 17:03 UTC, ArgjentG approved these changes

2024-11-10 17:03 UTC, ArgjentG approved these changes

2024-11-10 19:09 UTC, zealest reviewed
Traduire en français la show

2024-11-11 09:23 UTC, athanael requested changes

2024-11-11 09:23 UTC, athanael commented on app/views/users/show.html.erb
> +        <% track.comments.each do |comment| %>
Ajouter un bouton de déconnexion à côté du bouton My Spotify. Enlever la logique de back sur l'affichage des posts pour ne laisser que deux paragraphes dans leurs div Duration : et Comments:

2024-11-14 13:00 UTC, closed without merging